fallback = 'ï‹'

[matching]
'discord' = 'ï’'
'balena-etcher' = 'ï‹›'
'Chia Blockchain' = 'ï“˜'
'Steam' = 'ï†¶'
'vlc' = 'ï€½'
'org.qbittorrent.qBittorrent' = 'ï¶'
'Thunderbird' = 'ïƒ '
'thunderbird' = 'ïƒ '
'Postman' = 'ï '
'Insomnia' = 'ïˆ¶'
'Bitwarden' = 'ï‚„'
'Google-chrome' = 'ï‰¨'
'Chromium' = 'ï‰¨'
'Slack' = 'ï†˜'
'Code' = 'ï„¡'
'code-oss' = 'ï„¡'
'Spotify' = 'ï†¼'
'/(?i)Github.*Firefox/' = 'ï„“'
'firefox' = 'ï‰©'
'Nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'
'/nvim ?\w*/' = 'ï‰½'
'/npm/' = 'ï¹'
'/node/' = 'ï¹'
'/yarn/' = 'ï¹'
'Alacritty' = 'ï„ '
'foot' = 'ï„ '
'org.qutebrowser.qutebrowser' = 'ğŸŒ'
